{% set name = "sphinxcontrib-autoyaml" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6a56f93878735170e5504ca3030250960adafaffa7fb0d7177223d597874e9e9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - poetry-core >=1.0.0
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ruamel.yaml >=0.16.12
    - sphinx >=3.5.1,<6

test:
  imports:
    - sphinxcontrib
  commands:
    - pip list | grep -E "{{ name }}\s+{{ version }}"
  requires:
    - pip
    - m2-grep  # [win]

about:
  home: https://github.com/Jakski/sphinxcontrib-autoyaml
  summary: Sphinx autodoc extension for documenting YAML files from comments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
